<?php
/**
 * @var $block \Danaluc\CustomLogsViewer\Block\Adminhtml\View\LogViewer\LogFiles
 */
?>
<div class="admin__field">
    <label class="admin__field-label"><span><?= $block->escapeHtml(__('Custom logs files')) ?></span></label>
    <div class="admin__field-control">
        <?= $block->getChildHtml('log_files') ?>
        <button id="connector-log-restart" style="margin-left: 5px;">
            <span><?= $block->escapeHtml(__('Clean file')); ?></span>
        </button>
    </div>
    <div class="message message-success success" id="clean-file-result-container" style="padding: 10px 0px; margin-top: 10px; visibility: hidden;">
        <p id="clean-file-result-message" style="margin-left: 50px"></p>
    </div>
</div>

<div style="padding-top: 25px;">
    <h3 id="custom-log-header" style="border-bottom: 4px solid #dfdfdf; color: #eb5e00;">
        <?= $block->escapeHtml($block->getLogFileLabel()); ?>
    </h3>
</div>

<div style="margin-top: 20px; border: 4px solid #dfdfdf; overflow: hidden; height: 510px; padding: 5px;">
    <div id="log_file_data"
         style="width:100%;height:500px;overflow:auto;margin:0;padding:3px;background:black;color:#2EC029;
         font:normal 11px Lucida Console, Courier New, serif;">
        <?php /** $block \Danaluc\CustomLogsViewer\Block\Adminhtml\View\LogViewer\LogFiles */ ?>
        <?= /* @noEscape */ $block->getLogFileContent(); ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Danaluc_CustomLogsViewer/js/logViewUpdater":{
                "urlcontent":"<?= $block->escapeUrl($block->getAjaxLoadContentUrl()) ?>",
                "urlreset":"<?= $block->escapeUrl($block->getAjaxResetContentUrl()) ?>"
            }
        }
    }
</script>
